# Site settings
title: CityCampCHA
email: brigade@openchattanooga.com
description: CityCampCHA is an unconference focused on innovation for municipal governments and community organizations.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://citycampcha.com" # the base hostname & protocol for your site
domain: "citycampcha.com"
twitter_username: openchattanooga
github_username:  openchattanooga

# Build settings
markdown: kramdown

sass:
    style: :compressed
